sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: QG/xjIKCrgkdmx5V5dTen05Ylq6PGNf8O11sD725xoeicXRJWcUN2wHg0HUJe+7Z9fabI6yJeIiyaW2SLojLRKOVpCukNoR2rWsMt1lsscuKGZvD3Ku2fm9TXZkiKSLv8H4YU8JV+wnZZrW4BpyP185FDr0s+l3SUBrPtFAXhM8ad/JNlR9SUclFkSectk3IDcQQn2huJbPR8zCU8yT6NlnT5lvtyPyoQo1dzfKfkts5NhDHkL6VWmk1/UR+tZy9JAPVzOt/OXa9HJdLIDN/qKAsUDAuwbKhjcazWW4Oa5Wj3vt5MndZGz3vNyJ8Jg64iL6MhK+7B7GpmFKDHH2t7xkkmvsY4XtVO7wBABdS7f8wXVTi8zZJqYijIodbcTDw687GJ0ZE77T4jbWUa6lql3U3n2mmThxo87Pcf0FrMEDJsEg55AuutBzc4YpS0isDle8/5qQtKp93JSUVNErB1PWKeU1lCY58O5vZseK9czCo2HWFKbqkxr95RIOS+zSl/E0wNEoJpqin4nglIilIw+NU3vvwSj3dO3rnA6XwIGvLH/GCLgYNKEFfdLo74Eu1JcPbp5CGlbkjHVyP59TONq/zPpoCbhEyXsu///6zLgYaBksTDpTe4mQQ38Jp9IDAyRRv8u0n692kAo+bsNwJhNmEi0GHpRabVYCMPehsRqs=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: AZTrOBqJQ83phRbIzfikDkv6FuQ1JXpSDSb6/2TX/PMMkwUL6jD65he/+fOnsKHRIaEraQIQwwnVCE7E1XcdfyixMH9VrSDdgRuHITW/wmcv6UpjYt68WkJAqmkNc6Tq6bkjOBhi7u6Qga8JWwiWHN/Jt0yotFXIdrcG4seR/giRpLBLwc2rmNF80FAOswWXI9uCmXwMY/Nj2KMRMwkoodiY2KjZoM4gujwDakyK2fW9QQN4uJR5FquF3kHHNgfE3U2mqdlu50reePcdvD+FJWWFZ3as0s+jQuTo8jOvzInBxcqTdLKYF0iYNrEY0OUJ5V4Y+pd/g9XNHy+RgIKjXmfK+/i8s/sIbJvYjSTHtjli0Oy2ctAA1lA93yn7NSr6BRMghXnI2904yANvMMXQLMQRZNhBx3u9d4bnodpq1Vmrxa4i82ySQt0uUZ5E0/2DBAxaiI/raOFc4zy4OJkXtrzqH9FDrDMByp3B3nDPEZ0JBlBRUQMOxCP9piMDpd3ExjNlQbm2otoS0i3FkKH5To9k5/ldyUCS/Mzr+A6mvrNQC2HhOHXN/+WCisOLL60xJeLjO40r76gPbPZ00Rxp0zphjWOkhRv9/EYN8/6Vgd+R4ttWFCQ2gmvQoQvxiXj6GPTHFcJ45zWEoUTeGpPRmoHRGYwa/Le/xkElvdPIZLU=
